<document>
    <table aligns={[null, null]}>
        <table_row>
            <table_cell>A</table_cell>
            <table_cell>B</table_cell>
        </table_row>
        <table_row>
            <table_cell>
                <CODE>A1</CODE>
            </table_cell>
            <table_cell>B1</table_cell>
        </table_row>
        <table_row>
            <table_cell>
                <BOLD>A2</BOLD>
            </table_cell>
            <table_cell>B2</table_cell>
        </table_row>
    </table>
</document>
