<document>
    <table>
        <table_row>
            <table_cell>John</table_cell>
            <table_cell>Doe</table_cell>
        </table_row>
        <table_row>
            <table_cell>Jane</table_cell>
            <table_cell>Doe</table_cell>
        </table_row>
    </table>
</document>
